# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=8)),
                ('ask', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('bid', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('last', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
